# Dependencies
#markdown:         redcarpet
#pygments:         true

# Permalinks
permalink:        pretty

# Setup
title:            A blog by goofygrin
tagline:          12
url:              http://goofygrin.github.io
paginate:         5
author:
  name:           Sean Goodpasture
  url:            https://twitter.com/g00fygrin
  email:          goofygrin@gmail.com

# Custom vars
version:          1.0.0
github:
  repo:           https://github.com/goofygrin/goofygrin